server:
  port: 8080

zuul:
  routes:
    heroes:
      url: https://microservice-discipline-1.herokuapp.com/heroes
    countries:
      url: https://microservice-discipline-2.herokuapp.com/countries
    